export const MIDIControlEventNames = [
  "Bank Select",
  "Modulation",
  "Breath Controller",
  "Foot Pedal",
  "Portamento Time",
  "Data Entry",
  "Volume",
  "Balance",
  "Pan",
  "Expression",
  "Effect Control 1",
  "Effect Control 2",
  "Undefined",
  "Undefined",
  "General Purpose Slider 1",
  "General Purpose Slider 2",
  "General Purpose Slider 3",
  "Knob 2 General Purpose Slider 4",
  "Knob 3",
  "Knob 4",
  "Bank Select",
  "Modulation Wheel",
  "Breath controller",
  "Foot Pedal",
  "Portamento Time",
  "Data Entry",
  "Volume",
  "Balance",
  "Pan position",
  "Expression",
  "Effect Control 1",
  "Effect Control 2",
  "Hold Pedal",
  "Portamento",
  "Sustenuto Pedal",
  "Soft Pedal",
  "Legato Pedal",
  "Hold 2 Pedal",
  "Sound Variation",
  "Resonance",
  "Sound Release Time",
  "Sound Attack Time",
  "Frequency Cutoff",
  "Sound Control 6",
  "Sound Control 7",
  "Sound Control 8",
  "Sound Control 9",
  "Sound Control 10",
  "Decay",
  "High Pass Filter Frequency",
  "General Purpose Button 3",
  "General Purpose Button 4",
  "Reverb Level",
  "Tremolo Level",
  "Chorus Level",
  "Detune",
  "Phaser Level",
  "Data Button Increment",
  "Data Button Decrement",
  "NRPN (LSB)",
  "NRPN (MSB)",
  "RPN (LSB)",
  "RPN (MSB)",
  "All Sound Off",
  "All Controllers Off",
  "Local Keyboard",
  "All Notes Off",
  "Omni Mode Off",
  "Omni Mode On",
  "Mono Operation",
  "Poly Operation"
]
