name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: npm install, build and test
        run: |
          npm install
          npm run test
